services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - IWASSISTANT_DISCORD_TOKEN=
    command: /bin/sh -c "npm install && npm run dev"
